pizzas/urls.py
from django.urls import path

from . import views

app_name = 'pizzas'

urlpatterns = [
    path('',views.index, name='index'),
    path('pizzas',views.pizzas, name='pizzas'),
]

pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/models.py
from django.db import models

# Create your models here.


class Pizza(models.Model):
    name = models.CharField(max_length=200)
    #date_added = models.DateTimeField(auto_now_add=True)
    #owner = models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Topping(models.Model):
    pizza = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    name = models.TextField()
    #date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
   

pizzas/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    '''The home page for Pizzeria. '''
    return render(request, 'pizzas/index.html')


def pizzas(request):
    pizzas = Pizza.objects

    context = {'pizzas':pizzas}

    return render(request, 'pizzas/pizzas.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Papa Bho's</a>
    <a href="{% url 'pizzas:pizzas' %}">Pizzas</a>
</p>

{% block content %}

{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>The greatest Pizza Py(thon) in Waco!
</p>


{% endblock content %}

pizzas/templates/pizzas/pizzas.html
{% extends "pizzas/base.html" %}

{% block content %}

<p>Pizzas</p>

<ul>
    {% for pizza in pizzas %}

    <li>
        {{ pizza }}
    </li>
    {% empty %}
    <li> No pizzas have been added yet.</li>

    {% endfor %}
</ul>


{% endblock content %}